port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - 其他国家
      - 负载均衡
      - 失败切换
      - DIRECT
  - name: 手动选择
    type: select
    proxies:
  - name: 漏网之鱼
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - 其他国家
      - REJECT
      - DIRECT
  - name: 社交服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 谷歌服务
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 全球媒体
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: Emby视频
    type: select
    proxies:
      - 节点选择
      - 美国节点
      - 香港节点
      - 狮城节点
      - DIRECT
  - name: 美国节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 香港节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 狮城节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 其他国家
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
  - name: 自动选择
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 50
    proxies:
  - name: 负载均衡
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  - name: 失败切换
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:

rule-providers: # rule-providers from Logyalsoldier/clash-rules and LM-Firefly/Rules
  Applications:
    type: http
    behavior: classical # https://github.com/Dreamacro/clash/issues/1165
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/TopFreeProxies/applications.yaml
  Apple:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/TopFreeProxies/apple.yaml
  iCloud:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/TopFreeProxies/icloud.yaml
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/LM-Firefly/Rules@master/Clash-RuleSet-Classical/Microsoft.yaml
    path: ./ruleset/TopFreeProxies/microsoft.yaml
    interval: 86400
  Google:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/TopFreeProxies/google.yaml
    interval: 86400
  GlobalMedia:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/LM-Firefly/Rules@master/Clash-RuleSet-Classical/GlobalMedia.yaml
    path: ./ruleset/TopFreeProxies/globalmedia.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/TopFreeProxies/telegramcidr.yaml
    interval: 86400
  Twitter:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/LM-Firefly/Rules@master/Clash-RuleSet-Classical/PROXY/Twitter.yaml
    path: ./ruleset/TopFreeProxies/twitter.yaml
    interval: 86400
  Private:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/TopFreeProxies/private.yaml
    interval: 86400
  Local-LAN:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/LM-Firefly/Rules@master/Clash-RuleSet-Classical/Special/Local-LAN.yaml
    path: ./ruleset/TopFreeProxies/local-lan.yaml
    interval: 86400
  Proxy:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/TopFreeProxies/proxy.yaml
    interval: 86400
  Reject:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/TopFreeProxies/reject.yaml
    interval: 86400
rules:
  - RULE-SET,Applications,DIRECT
  - IP-CIDR,10.240.0.0/24,DIRECT,no-resolve
  - IP-CIDR,192.168.123.0/24,DIRECT,no-resolve
  - DOMAIN-SUFFIX,emby.wtf,Emby视频,no-resolve
  - DOMAIN-SUFFIX,bitwarden.net,DIRECT,no-resolve
  - DOMAIN-SUFFIX,bitwarden.com,DIRECT,no-resolve

  - RULE-SET,Local-LAN,DIRECT,no-resolve
  - RULE-SET,Reject,REJECT,no-resolve
  - RULE-SET,Private,DIRECT,no-resolve
  - RULE-SET,Apple,苹果服务
  - RULE-SET,iCloud,苹果服务
  - RULE-SET,Microsoft,微软服务
  - RULE-SET,GlobalMedia,全球媒体
  - RULE-SET,Google,谷歌服务
  - RULE-SET,Twitter,社交服务
  - RULE-SET,Telegram,社交服务

  - GEOIP,CN,DIRECT
  - RULE-SET,Proxy,节点选择
  - MATCH,漏网之鱼
